### PR TITLE
In memory implementation

### PR DESCRIPTION
**Pull request by panditpakhurde**
Have Implement FeedStore Infrastructure with 'InMemory' persistent stack (Swift Array). Please verify the same. Please provide the feed back and let me know in case of any code improvement.

### CODE REVIEW

**Comment by caiozullo** [comment]
Hi @devessentials20,

Congratulations, you've passed the challenge! 🥇

- All tests are passing, so your implementation complies with the specs.
- Your code is clean and well organized.
- You broke down the implementation in small commits.
- You added the diagram and explained your solution well in the `README`.

Great job ✅

**Comment by devessentials20** [comment]
Thank you for the review. :)

**Comment by caiozullo** [comment]
Nice one!

**Comment by devessentials20** [comment]
> Nice one!

Thank you 🙂

**Pull request closed without merging**
