### PR TITLE
Realm Implementation

### PR DESCRIPTION
**Pull request by bassgey**
Finally I did!

Last three commits are only to solve the Github problems.
If it can help someone, this solved my problem with the forgotten fork:
https://gist.github.com/ElectricRCAircraftGuy/8ca9c04924ac11a50d48c2061d28b090

Bye

### CODE REVIEW

**Comment by bassgey** [comment]
Failing check...
I have used cocoapods to install the Realm framework, maybe this is the problem...

**Comment by caiozullo** [comment]
Hi @bassgey, if you're using cocoapods, you need to update the `xcodebuild` command in the `.travis.yml` config to build with the `.xcworkspace` generated by cocoapods (instead of the `.xcodeproj`)

You can run that command in the command-line before pushing. If it works locally, it should work on CI.

Please, let me know when you fix it. Thanks! ✅

**Comment by bassgey** [comment]
Ok, fixed the script. 
I can build and run on my workstation.

**Comment by caiozullo** [comment]
Hi @bassgey, 

Congratulations you've passed the challenge 🥇

Your implementation complies with the specs. ✅
You added integration tests. ✅
You added the Dependency Diagram. ✅
All tests are passing on the CI server. ✅

Good job!

**Pull request closed without merging**
